source 'https://cdn.cocoapods.org/'

platform :ios, '16.0'

target 'iosApp' do
  use_frameworks!
  pod 'YandexMobileAds', '8.3.0'
  pod 'AppMetricaCore', '6.6.0'
  pod 'MintegralYandexMobileAdsAdapters', '8.0.7.3'
end
