[versions]
applicationId = "ru.aleshin.studyassistant"
minSdk = "24"
targetSdk = "37"
compileSdk = "37"
jvmTarget = "17"
version-name = "1.1.0"
version-code = "5"
testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

# Gradle
agp = "9.3.0"
ksp = "2.3.11"

# Kotlin
kotlin = "2.4.10"
kotlin-coroutines = "1.11.0"
kotlin-serialization = "1.11.0"
kotlin-datetime = "0.7.1"
kotlin-io = "0.9.1"
kotlin-atomic = "0.33.0"
kotlin-immutable = "0.5.1"

# Swift
skie = "0.10.14"
swiftklib = "0.6.4"

# Compose
compose = "1.11.2"
compose-bom = "2026.06.01"
compose-material = "1.14.0"
compose-material3 = "1.4.0"
compose-adaptive = "1.3.0-beta02"
compose-multiplatform = "1.11.1"

# UI
richtext = "0.43.0"
placeholder = "1.0.12"
drag-and-drop = "0.5.0"
koalaplot-charts = "0.12.0"
charty = "3.0.0-rc01"
sketch = "4.6.0"
guava = "33.6.0-android"

# AndroidX
androidx-activity-compose = "1.13.0"
androidx-browser = "1.10.0"
androidx-core-ktx = "1.19.0"
androidx-workmanager = "2.11.2"
androidx-paging = "3.5.0"
androidx-camera = "1.6.1"
androidx-exifinterface = "1.4.2"
androidx-glance = "1.1.1"
zxing = "3.5.4"

# Google
google-accompanist = "0.36.0"
paddleocr = "1.6.0"

# RuStore
rustore-review = "10.5.0"
rustore-updates = "10.5.0"
yandex-ads = "8.1.0"
mytarget-ads = "5.45.3.4"

# Crashlytics & Analytics
tracer = "1.4.0"
mytracker = "3.6.0"

# DI
kodein = "7.33.0"

# Decompose & Essenty
decompose = "3.5.0"
essenty = "2.5.0"

# Ktor
ktor = "3.5.2"

# Databases
sqldelight = "2.3.2"
settings = "1.3.0"

# Multiplatform Utils
bignum = "0.3.10"
logger-kermit = "2.1.0"
konnektion = "1.4.5"
filekit = "0.14.2"
konfig = "0.22.0"

[libraries]

# Kotlin
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlin-atomic" }
kotlin-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlin-io" }
kotlin-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlin-immutable" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { group = "com.google.android.material", name = "material", version.ref = "compose-material" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "compose-adaptive" }
compose-material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "compose-adaptive" }

# Ui
richtext = { module = "com.mikepenz:multiplatform-markdown-renderer", version.ref = "richtext" }
richtext-material3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "richtext" }
placeholder = { group = "com.eygraber", name = "compose-placeholder-material3", version.ref = "placeholder" }
koalaplot-charts = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplot-charts" }
charty = { module = "com.himanshoe:charty", version.ref = "charty" }
dragAndDrop = { module = "com.mohamedrejeb.dnd:compose-dnd", version.ref = "drag-and-drop" }
sketch-compose = { module = "io.github.panpf.sketch4:sketch-compose", version.ref = "sketch" }
sketch-http = { module = "io.github.panpf.sketch4:sketch-http", version.ref = "sketch" }
sketch-ktor = { module = "io.github.panpf.sketch4:sketch-http-ktor3", version.ref = "sketch" }
sketch-compose-resources = { module = "io.github.panpf.sketch4:sketch-compose-resources", version.ref = "sketch" }
sketch-compose-extnsions-resources = { module = "io.github.panpf.sketch4:sketch-extensions-compose-resources", version.ref = "sketch" }

# AndroidX
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-workmanager = { module = "androidx.work:work-runtime", version.ref = "androidx-workmanager" }
androidx-workmanager-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-workmanager" }
androidx-guava = { module = "com.google.guava:guava", version.ref = "guava" }
androidx-tools = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camera" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "androidx-exifinterface" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidx-glance" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing" }

# Google
google-accompanist = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "google-accompanist" }

google-mlkit-text-recognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version = "19.0.0" }

# RuStore
rustore-review = { module = "ru.rustore.sdk:review", version.ref = "rustore-review" }
rustore-updates = { module = "ru.rustore.sdk:appupdate", version.ref = "rustore-updates" }

# Yandex
yandex-ads-multiplatform = { module = "com.yandex.ads.multiplatform:mobileads-compose", version.ref = "yandex-ads" }
yandex-ads-core = { module = "com.yandex.android:mobileads", version.ref = "yandex-ads" }
yandex-ads-compose = { module = "com.yandex.android:mobileads-compose", version.ref = "yandex-ads" }
yandex-ads-mytarget = { module = "com.yandex.ads.mediation:mobileads-mytarget", version.ref = "mytarget-ads" }

# Crashlytics & Analytics
tracer-bom = { module = "ru.ok.tracer:tracer-platform", version.ref = "tracer" }
tracer-crashReport = { module = "ru.ok.tracer:tracer-crash-report" }
tracer-crashReportNative = { module = "ru.ok.tracer:tracer-crash-report-native" }
tracer-heapDumps = { module = "ru.ok.tracer:tracer-heap-dumps" }
tracer-diskUsage = { module = "ru.ok.tracer:tracer-disk-usage" }
tracer-samplingProfiler = { module = "ru.ok.tracer:tracer-profiler-sampling" }
tracer-systraceProfiler = { module = "ru.ok.tracer:tracer-profiler-systrace" }
mytracker-core = { module = "com.my.tracker:mytracker-sdk", version.ref = "mytracker" }

# DI
kodein-core = { module = "org.kodein.di:kodein-di", version.ref = "kodein" }
kodein-compose = { module = "org.kodein.di:kodein-di-framework-compose", version.ref = "kodein" }
kodein-android = { module = "org.kodein.di:kodein-di-framework-android-core", version.ref = "kodein" }

# Decompose
decompose-core = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-compose-experimental = { module = "com.arkivanov.decompose:extensions-compose-experimental", version.ref = "decompose" }
decompose-lifecycle-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.ref = "essenty" }
decompose-essenty-lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }
decompose-essenty-statekeeper = { module = "com.arkivanov.essenty:state-keeper", version.ref = "essenty" }
decompose-essenty-instancekeeper = { module = "com.arkivanov.essenty:instance-keeper", version.ref = "essenty" }
decompose-essenty-backhandler = { module = "com.arkivanov.essenty:back-handler", version.ref = "essenty" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }

# Databases
sqldelight-core = { module = "app.cash.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-async = { module = "app.cash.sqldelight:async-extensions", version.ref = "sqldelight" }
sqldelight-prmimitiveAdapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-desktop = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
settings-core = { module = "com.russhwolf:multiplatform-settings", version.ref = "settings" }
settings-noargs = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "settings" }

# Multiplatform Utils
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }
logger = { module = "co.touchlab:kermit", version.ref = "logger-kermit" }
networkcheker = { module = "dev.tmapps:konnection", version.ref = "konnektion" }
filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }


[bundles]
decompose = ["decompose-core", "decompose-compose", "decompose-compose-experimental", "decompose-lifecycle-coroutines"]
essenty = ["decompose-essenty-lifecycle", "decompose-essenty-backhandler", "decompose-essenty-instancekeeper", "decompose-essenty-statekeeper"]
sketch = ["sketch-compose", "sketch-compose-resources", "sketch-compose-extnsions-resources", "sketch-http", "sketch-ktor"]
tracer = ["tracer-crashReport", "tracer-crashReportNative", "tracer-heapDumps", "tracer-diskUsage", "tracer-samplingProfiler", "tracer-systraceProfiler"]
filekit = ["filekit-core", "filekit-compose"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
swiftklib = { id = "io.github.ttypic.swiftklib", version.ref = "swiftklib" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
konfig = { id = "com.codingfeline.buildkonfig", version.ref = "konfig" }
tracer = { id = "ru.ok.tracer", version.ref = "tracer" }
