/*
 * Copyright 2024 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ru.aleshin.studyassistant.editor.impl.presentation.theme.tokens

import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.studyassistant.core.ui.theme.tokens.StudyAssistantLanguage

/**
 * @author Stanislav Aleshin on 27.05.2024.
 */
internal data class EditorStrings(
    val weekScheduleEditorHeader: String,
    val dailyScheduleEditorHeader: String,
    val classEditorHeader: String,
    val subjectEditorHeader: String,
    val employeeEditorHeader: String,
    val organizationEditorHeader: String,
    val homeworkEditorHeader: String,
    val profileEditorHeader: String,
    val todoEditorHeader: String,
    val saveButtonTitle: String,
    val numberOfClassesLabel: String,
    val standardTimeIntervalHeader: String,
    val classesTitle: String,
    val breaksTitle: String,
    val scheduleIntervalsDialogHeader: String,
    val startOfClassesTitle: String,
    val startOfClassesPlaceholder: String,
    val exceptTitle: String,
    val allTitle: String,
    val addTitle: String,
    val quantityOfClassesTitle: String,
    val numberOfClassTitle: String,
    val durationTitle: String,
    val organizationFieldLabel: String,
    val organizationFieldPlaceholder: String,
    val organizationSelectorHeader: String,
    val organizationSelectorTitle: String,
    val eventTypeFieldLabel: String,
    val eventTypeFieldPlaceholder: String,
    val eventTypeSelectorHeader: String,
    val eventTypeSelectorTitle: String,
    val subjectFieldLabel: String,
    val subjectFieldPlaceholder: String,
    val subjectSelectorHeader: String,
    val subjectSelectorTitle: String,
    val teacherFieldLabel: String,
    val teacherFieldPlaceholder: String,
    val teacherSelectorHeader: String,
    val teacherSelectorTitle: String,
    val locationFieldLabel: String,
    val locationFieldPlaceholder: String,
    val locationSelectorHeader: String,
    val locationSelectorTitle: String,
    val officeFieldLabel: String,
    val officeFieldPlaceholder: String,
    val officeSelectorHeader: String,
    val officeSelectorTitle: String,
    val startTimeFieldLabel: String,
    val startTimeFieldPlaceholder: String,
    val endTimeFieldLabel: String,
    val endTimeFieldPlaceholder: String,
    val notificationParamsLabel: String,
    val notificationParamsTitle: String,
    val notCollectedTimeData: String,
    val subjectNameFieldLabel: String,
    val subjectNameFieldPlaceholder: String,
    val colorPickerLabel: String,
    val firstNameFieldLabel: String,
    val secondNameFieldLabel: String,
    val patronymicFieldLabel: String,
    val employeePostFieldLabel: String,
    val employeePostFieldPlaceholder: String,
    val employeePostSelectorHeader: String,
    val employeePostSelectorTitle: String,
    val birthdayFieldLabel: String,
    val birthdayFieldPlaceholder: String,
    val emailFieldLabel: String,
    val emailFieldPlaceholder: String,
    val phoneFieldLabel: String,
    val phoneFieldPlaceholder: String,
    val webFieldLabel: String,
    val webFieldPlaceholder: String,
    val contactInfoSectionHeader: String,
    val homeworkDatePickerHeadline: String,
    val homeworkDateFieldLabel: String,
    val homeworkDateFieldPlaceholder: String,
    val linkClassViewTitle: String,
    val linkClassViewEmptyTitle: String,
    val theoryFieldLabel: String,
    val theoryFieldPlaceholder: String,
    val practiceFieldLabel: String,
    val practiceFieldPlaceholder: String,
    val presentationsFieldLabel: String,
    val presentationsFieldPlaceholder: String,
    val testFieldLabel: String,
    val testFieldPlaceholder: String,
    val priorityViewTitle: String,
    val standardPriorityItemTitle: String,
    val mediumPriorityItemTitle: String,
    val highPriorityItemTitle: String,
    val numberOfClassSuffix: String,
    val taskTitle: String,
    val shortNameFieldLabel: String,
    val fullNameFieldLabel: String,
    val orgTypeFieldLabel: String,
    val orgTypeSelectorHeader: String,
    val orgTypeFieldPlaceholder: String,
    val organizationStatusTitle: String,
    val fastEditDailyScheduleHeader: String,
    val fastEditStartOfDayLabel: String,
    val startOfDayDialogHeader: String,
    val startOfDayDialogTitle: String,
    val fastEditClassesDurationLabel: String,
    val classesDurationDialogHeader: String,
    val classesDurationDialogTitle: String,
    val fastEditBreaksDurationLabel: String,
    val breaksDurationDialogHeader: String,
    val breaksDurationDialogTitle: String,
    val returnScheduleTitle: String,
    val editCustomScheduleTitle: String,
    val noneClassesTitle: String,
    val customScheduleDateTitle: String,
    val shiftTimeError: String,
    val todoNameFieldLabel: String,
    val todoNameFieldPlaceholder: String,
    val todoDescriptionFieldLabel: String,
    val todoDescriptionFieldPlaceholder: String,
    val todoDeadlineFieldLabel: String,
    val todoDeadlineFieldPlaceholder: String,
    val todoDeadlineDatePickerHeadline: String,
    val todoTimeFieldLabel: String,
    val todoTimeFieldPlaceholder: String,
    val todoNotificationTitle: String,
    val todoNotificationLabel: String,
    val todoNotifyParamsBeforeStart: String,
    val todoNotifyParamsBeforeFifteenMinutes: String,
    val todoNotifyParamsBeforeOneHour: String,
    val todoNotifyParamsBeforeThreeHour: String,
    val todoNotifyParamsBeforeOneDay: String,
    val todoNotifyParamsBeforeOneWeek: String,
    val usernameFieldLabel: String,
    val usernameFieldPlaceholder: String,
    val userDescriptionFieldLabel: String,
    val userDescriptionFieldPlaceholder: String,
    val userGenderFieldLabel: String,
    val userGenderFieldPlaceholder: String,
    val cityFieldLabel: String,
    val cityFieldPlaceholder: String,
    val socialNetworkLabel: String,
    val socialNetworkServiceLabel: String,
    val socialNetworkServicePlaceholder: String,
    val otherSocialNetworkServiceNameLabel: String,
    val socialNetworkPlaceholder: String,
    val changePasswordActionLabel: String,
    val passwordChangerLabel: String,
    val oldPasswordFieldLabel: String,
    val passwordFieldPlaceholder: String,
    val credentialsErrorMessage: String,
    val hideOrganizationWarning: String,
    val deleteOfficeWarningTitle: String,
    val deleteLocationWarningTitle: String,
    val subjectsSearchBarPlaceholder: String,
    val employeeSearchBarPlaceholder: String,
    val otherErrorMessage: String,
) {
    companion object {
        val RUSSIAN = EditorStrings(
            weekScheduleEditorHeader = "Редактор расписания",
            dailyScheduleEditorHeader = "Редактор дня",
            classEditorHeader = "Редактор событий",
            subjectEditorHeader = "Редактор предметов",
            employeeEditorHeader = "Редактор сотрудника",
            organizationEditorHeader = "Редактор организации",
            homeworkEditorHeader = "Редактор заданий",
            profileEditorHeader = "Профиль",
            todoEditorHeader = "Редактор задач",
            saveButtonTitle = "Сохранить",
            numberOfClassesLabel = "Количество занятий",
            standardTimeIntervalHeader = "Стандартные значения",
            classesTitle = "Занятия",
            breaksTitle = "Перерывы",
            scheduleIntervalsDialogHeader = "Стандартные значения",
            startOfClassesTitle = "Начало занятий",
            startOfClassesPlaceholder = "Введите нужное время",
            exceptTitle = "Кроме",
            allTitle = "Все",
            addTitle = "Добавить",
            quantityOfClassesTitle = "Кол-во:",
            numberOfClassTitle = "Номер",
            durationTitle = "Длительность",
            organizationFieldLabel = "Организация",
            organizationFieldPlaceholder = "Выберите организацию",
            organizationSelectorHeader = "Организация",
            organizationSelectorTitle = "Выберите необходимую организацию",
            eventTypeFieldLabel = "Событие",
            eventTypeFieldPlaceholder = "Выберите формат проведения",
            eventTypeSelectorHeader = "Событие",
            eventTypeSelectorTitle = "Выберите формат проведения",
            subjectFieldLabel = "Предмет",
            subjectFieldPlaceholder = "Выберите предмет",
            subjectSelectorHeader = "Предмет",
            subjectSelectorTitle = "Выберите необходимый предмет",
            teacherFieldLabel = "Преподаватель",
            teacherFieldPlaceholder = "Выберите преподавателя",
            teacherSelectorHeader = "Преподаватель",
            teacherSelectorTitle = "Выберите преподавателя занятия",
            locationFieldLabel = "Место",
            locationFieldPlaceholder = "Укажите место",
            locationSelectorHeader = "Место",
            locationSelectorTitle = "Укажите место проведения",
            officeFieldLabel = "Кабинет",
            officeFieldPlaceholder = "000",
            officeSelectorHeader = "Кабинет",
            officeSelectorTitle = "Укажите кабинет",
            startTimeFieldLabel = "Начало",
            startTimeFieldPlaceholder = "00:00",
            endTimeFieldLabel = "Конец",
            endTimeFieldPlaceholder = "23:59",
            notificationParamsTitle = "Особые уведомления",
            notificationParamsLabel = "Исключительно уведомлять о начале и конце события",
            notCollectedTimeData = "Не удалось собрать данные",
            subjectNameFieldLabel = "Название",
            subjectNameFieldPlaceholder = "Введите название предмета",
            colorPickerLabel = "Цвет",
            firstNameFieldLabel = "Имя *",
            secondNameFieldLabel = "Фамилия",
            patronymicFieldLabel = "Отчество",
            employeePostFieldLabel = "Должность *",
            employeePostFieldPlaceholder = "Выберите должность",
            employeePostSelectorHeader = "Должность",
            employeePostSelectorTitle = "Выберите должность сотрудника",
            birthdayFieldLabel = "День рождения",
            birthdayFieldPlaceholder = "Укажите день рождения",
            emailFieldLabel = "Email",
            emailFieldPlaceholder = "example@example.com",
            phoneFieldLabel = "Телефон",
            phoneFieldPlaceholder = "0-000-000-00-00",
            webFieldLabel = "Сайт",
            webFieldPlaceholder = "www.example.com",
            contactInfoSectionHeader = "Связь и данные",
            homeworkDatePickerHeadline = "День расписания",
            homeworkDateFieldLabel = "Дата",
            homeworkDateFieldPlaceholder = "Укажите дату дедлайна",
            linkClassViewTitle = "Привязка занятия",
            linkClassViewEmptyTitle = "Выберите предмет чтобы продолжить",
            theoryFieldLabel = "Теория",
            theoryFieldPlaceholder = "Заголовок: a, b; Заголовок: c",
            practiceFieldLabel = "Практика",
            practiceFieldPlaceholder = "Заголовок: a, b. Заголовок: c",
            presentationsFieldLabel = "Доклады",
            presentationsFieldPlaceholder = "Заголовок: a, b | Заголовок: c",
            testFieldLabel = "Тест",
            testFieldPlaceholder = "Введите тему работы",
            priorityViewTitle = "Приоритет",
            standardPriorityItemTitle = "Обычный",
            mediumPriorityItemTitle = "Средний",
            highPriorityItemTitle = "Макс.",
            numberOfClassSuffix = "занятие",
            taskTitle = "Задание",
            shortNameFieldLabel = "Краткое название *",
            fullNameFieldLabel = "Полное название",
            orgTypeFieldLabel = "Вид организации *",
            orgTypeFieldPlaceholder = "Укажите вид организации",
            orgTypeSelectorHeader = "Вид организации",
            organizationStatusTitle = "Основная организация",
            fastEditDailyScheduleHeader = "Быстрое редактирование",
            fastEditStartOfDayLabel = "Начало дня",
            startOfDayDialogHeader = "Начало дня",
            startOfDayDialogTitle = "Сдвиг всех занятий относительно 1 занятия",
            fastEditClassesDurationLabel = "Длительность занятий",
            classesDurationDialogHeader = "Занятия",
            classesDurationDialogTitle = "Измените длительность занятий",
            fastEditBreaksDurationLabel = "Длительность перерывов",
            breaksDurationDialogHeader = "Перерывы",
            breaksDurationDialogTitle = "Измените длительность перерывов",
            returnScheduleTitle = "Вернуть",
            editCustomScheduleTitle = "Начать редактировать",
            noneClassesTitle = "Занятия отсутствуют",
            customScheduleDateTitle = "Дата",
            todoNameFieldLabel = "Задача *",
            todoNameFieldPlaceholder = "Введите вашу задачу",
            todoDescriptionFieldLabel = "Описание",
            todoDescriptionFieldPlaceholder = "Введите описание",
            todoDeadlineFieldLabel = "Дата",
            todoDeadlineFieldPlaceholder = "Укажите дату дедлайна",
            todoDeadlineDatePickerHeadline = "Дедлайн задачи",
            todoTimeFieldLabel = "Время",
            todoTimeFieldPlaceholder = "Укажите время дедлайна",
            todoNotificationTitle = "Уведомления",
            todoNotificationLabel = "Уведомлять за настроенный промежуток времени",
            todoNotifyParamsBeforeStart = "В момент окончания",
            todoNotifyParamsBeforeFifteenMinutes = "За 15 минут",
            todoNotifyParamsBeforeOneHour = "За 1 час",
            todoNotifyParamsBeforeThreeHour = "За 3 часа",
            todoNotifyParamsBeforeOneDay = "За 1 день",
            todoNotifyParamsBeforeOneWeek = "За 1 неделю",
            usernameFieldLabel = "Отображаемое имя *",
            usernameFieldPlaceholder = "Имя Фамилия",
            userDescriptionFieldLabel = "Описание профиля",
            userDescriptionFieldPlaceholder = "Введите описание профиля",
            userGenderFieldLabel = "Пол",
            userGenderFieldPlaceholder = "Укажите ваш пол",
            cityFieldLabel = "Город",
            cityFieldPlaceholder = "Введите ваш город",
            socialNetworkLabel = "Соц сеть",
            socialNetworkServiceLabel = "Сервис",
            socialNetworkServicePlaceholder = "Выберите сервис из списка",
            otherSocialNetworkServiceNameLabel = "Название сервиса",
            socialNetworkPlaceholder = "Укажите соц сеть и @id",
            changePasswordActionLabel = "Изменить пароль",
            passwordChangerLabel = "Пароль",
            oldPasswordFieldLabel = "Старый пароль",
            passwordFieldPlaceholder = "Мин. 6 символов (a-Z)(0-9)",
            shiftTimeError = "Ошибка сдвига занятий! Нарушение временных рамок",
            credentialsErrorMessage = "Данные пользователя, неверны или неполны!",
            hideOrganizationWarning = "Вы уверены что хотите скрыть организацию? После этого вы больше не сможете её использовать",
            deleteOfficeWarningTitle = "Вы уверены что хотите удалить данный кабинет?",
            deleteLocationWarningTitle = "Вы уверены что хотите удалить данную локацию?",
            subjectsSearchBarPlaceholder = "Поиск предметов",
            employeeSearchBarPlaceholder = "Поиск преподавателей",
            otherErrorMessage = "Ошибка! Обратитесь к разработчику!",
        )
        val ENGLISH = EditorStrings(
            weekScheduleEditorHeader = "Schedule editor",
            dailyScheduleEditorHeader = "Daily editor",
            classEditorHeader = "Event editor",
            subjectEditorHeader = "Subject editor",
            employeeEditorHeader = "Employee editor",
            organizationEditorHeader = "Organization editor",
            homeworkEditorHeader = "Task editor",
            profileEditorHeader = "Profile",
            todoEditorHeader = "Todo editor",
            saveButtonTitle = "Save",
            numberOfClassesLabel = "Number of classes",
            standardTimeIntervalHeader = "Standard values",
            classesTitle = "Classes",
            breaksTitle = "Breaks",
            scheduleIntervalsDialogHeader = "Standard values",
            startOfClassesTitle = "Beginning of classes",
            startOfClassesPlaceholder = "Enter the desired time",
            exceptTitle = "Except",
            allTitle = "All",
            addTitle = "Add",
            quantityOfClassesTitle = "Quantity:",
            numberOfClassTitle = "Number",
            durationTitle = "Duration",
            organizationFieldLabel = "Organization",
            organizationFieldPlaceholder = "Select an organization",
            organizationSelectorHeader = "Organization",
            organizationSelectorTitle = "Select the desired organization",
            eventTypeFieldLabel = "Event",
            eventTypeFieldPlaceholder = "Choose event format",
            eventTypeSelectorHeader = "Event",
            eventTypeSelectorTitle = "Choose event format",
            subjectFieldLabel = "Subject",
            subjectFieldPlaceholder = "Choose a subject",
            subjectSelectorHeader = "Subject",
            subjectSelectorTitle = "Select the desired subject",
            teacherFieldLabel = "Teacher",
            teacherFieldPlaceholder = "Choose teacher",
            teacherSelectorHeader = "Teacher",
            teacherSelectorTitle = "Choose a class teacher",
            locationFieldLabel = "Location",
            locationFieldPlaceholder = "Specify event location",
            locationSelectorHeader = "Location",
            locationSelectorTitle = "Specify event location",
            officeFieldLabel = "Office",
            officeFieldPlaceholder = "000",
            officeSelectorHeader = "Office",
            officeSelectorTitle = "Specify the cabinet",
            startTimeFieldLabel = "Start",
            startTimeFieldPlaceholder = "00:00",
            endTimeFieldLabel = "End",
            endTimeFieldPlaceholder = "23:59",
            notificationParamsTitle = "Special notifications",
            notificationParamsLabel = "Exclusively notify about the beginning and end of the event",
            notCollectedTimeData = "Data could not be collected",
            subjectNameFieldLabel = "Name",
            subjectNameFieldPlaceholder = "Enter subject name",
            colorPickerLabel = "Color",
            firstNameFieldLabel = "First name *",
            secondNameFieldLabel = "Second name",
            patronymicFieldLabel = "Patronymic",
            employeePostFieldLabel = "Position *",
            employeePostFieldPlaceholder = "Choose a position",
            employeePostSelectorHeader = "Position",
            employeePostSelectorTitle = "Select an employee position",
            birthdayFieldLabel = "Birthday",
            birthdayFieldPlaceholder = "Specify birthday",
            emailFieldLabel = "Email",
            phoneFieldLabel = "Phone",
            webFieldLabel = "Web",
            contactInfoSectionHeader = "Communication and data",
            emailFieldPlaceholder = "example@example.com",
            phoneFieldPlaceholder = "0-000-000-00-00",
            webFieldPlaceholder = "www.example.com",
            homeworkDatePickerHeadline = "Schedule date",
            homeworkDateFieldLabel = "Date",
            homeworkDateFieldPlaceholder = "Specify the deadline",
            linkClassViewTitle = "Linking an class",
            linkClassViewEmptyTitle = "Select an subject to continue",
            theoryFieldLabel = "Theory",
            theoryFieldPlaceholder = "Title: a, b; Title: c",
            practiceFieldLabel = "Practice",
            practiceFieldPlaceholder = "Title: a, b. Title: c",
            presentationsFieldLabel = "Presentations",
            presentationsFieldPlaceholder = "Title: a, b | Title: c",
            testFieldLabel = "Test",
            testFieldPlaceholder = "Enter test topic",
            priorityViewTitle = "Priority",
            standardPriorityItemTitle = "Standard",
            mediumPriorityItemTitle = "Medium",
            highPriorityItemTitle = "Max",
            numberOfClassSuffix = "class",
            taskTitle = "Task",
            shortNameFieldLabel = "Short name *",
            fullNameFieldLabel = "Full name",
            orgTypeFieldLabel = "Type of organization *",
            orgTypeSelectorHeader = "Type of organization",
            orgTypeFieldPlaceholder = "Specify type of organization",
            organizationStatusTitle = "The main organization",
            fastEditDailyScheduleHeader = "Quick editing",
            fastEditStartOfDayLabel = "Start of the day",
            startOfDayDialogHeader = "Start of the day",
            startOfDayDialogTitle = "The shift of all classes relative to 1 class",
            fastEditClassesDurationLabel = "Duration of classes",
            classesDurationDialogHeader = "Classes",
            classesDurationDialogTitle = "Change the duration of classes",
            fastEditBreaksDurationLabel = "Duration of breaks",
            breaksDurationDialogHeader = "Breaks",
            breaksDurationDialogTitle = "Change the duration of breaks",
            returnScheduleTitle = "Return",
            editCustomScheduleTitle = "Start editing",
            noneClassesTitle = "Classes is missing",
            customScheduleDateTitle = "Date",
            todoNameFieldLabel = "Todo *",
            todoNameFieldPlaceholder = "Enter your todo",
            todoDescriptionFieldLabel = "Description",
            todoDescriptionFieldPlaceholder = "Enter вescription",
            todoDeadlineFieldLabel = "Date",
            todoDeadlineFieldPlaceholder = "Specify the deadline date",
            todoDeadlineDatePickerHeadline = "Todo deadline",
            todoTimeFieldLabel = "Time",
            todoTimeFieldPlaceholder = "Specify the deadline time",
            todoNotificationTitle = "Notifications",
            todoNotificationLabel = "Notify for a set period of time",
            todoNotifyParamsBeforeStart = "At the time of the end",
            todoNotifyParamsBeforeFifteenMinutes = "15 minutes before",
            todoNotifyParamsBeforeOneHour = "An hour before",
            todoNotifyParamsBeforeThreeHour = "Three hours before",
            todoNotifyParamsBeforeOneDay = "A day before",
            todoNotifyParamsBeforeOneWeek = "A week before",
            usernameFieldLabel = "Display name *",
            usernameFieldPlaceholder = "First and last name",
            userDescriptionFieldLabel = "Profile description",
            userDescriptionFieldPlaceholder = "Enter a profile description",
            cityFieldLabel = "City",
            cityFieldPlaceholder = "Enter your city",
            socialNetworkLabel = "Social network",
            socialNetworkServiceLabel = "Service",
            socialNetworkServicePlaceholder = "Select a service from the list",
            otherSocialNetworkServiceNameLabel = "Name of the service",
            socialNetworkPlaceholder = "Specify the social network and @id",
            userGenderFieldLabel = "Gender",
            userGenderFieldPlaceholder = "Specify your gender",
            changePasswordActionLabel = "Change the password",
            passwordChangerLabel = "Password",
            oldPasswordFieldLabel = "Old password",
            passwordFieldPlaceholder = "Min. 6 chars (a-Z)(0-9)",
            shiftTimeError = "Classes shift error! Violation of the time frame",
            credentialsErrorMessage = "The user's data seems to be incorrect or incomplete!",
            hideOrganizationWarning = "Are you sure you want to hide the organization? After that, you won't be able to use it anymore",
            deleteOfficeWarningTitle = "Are you sure you want to delete this office?",
            deleteLocationWarningTitle = "Are you sure you want to delete this location?",
            subjectsSearchBarPlaceholder = "Search for subjects",
            employeeSearchBarPlaceholder = "Search for teachers",
            otherErrorMessage = "Error! Contact the developer!",
        )
    }
}

internal val LocalEditorStrings = staticCompositionLocalOf<EditorStrings> {
    error("Editor Strings is not provided")
}

internal fun fetchEditorStrings(language: StudyAssistantLanguage) = when (language) {
    StudyAssistantLanguage.EN -> EditorStrings.ENGLISH
    StudyAssistantLanguage.RU -> EditorStrings.RUSSIAN
}