/*
 * Copyright 2024 Stanislav Aleshin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ru.aleshin.studyassistant.tasks.impl.presentation.theme.tokens

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import ru.aleshin.studyassistant.core.ui.theme.tokens.StudyAssistantLanguage

/**
 * @author Stanislav Aleshin on 27.05.2024.
 */
@Immutable
internal data class TasksStrings(
    val overviewHeader: String,
    val homeworksHeader: String,
    val todosHeader: String,
    val dailyGoalsSectionHeader: String,
    val goalsViewProgressTitle: String,
    val goalsViewProgressHomeworkLabel: String,
    val goalsViewProgressTodoLabel: String,
    val goalsViewClosestTitle: String,
    val goalsViewListTitle: String,
    val goalsViewListEmptyTitle: String,
    val deleteGoalWarningTitle: String,
    val deleteGoalWarningText: String,
    val goalCreatorHeadline: String,
    val goalCreatorTitle: String,
    val goalCreatorDateFieldTitle: String,
    val goalCreatorDateFieldPlaceholder: String,
    val goalCreatorDesiredTimeFieldTitle: String,
    val goalCreatorConfirmTitle: String,
    val goalSheetTimeControlTitle: String,
    val goalSheetDesiredTimeLabel: String,
    val goalSheetDesiredTimePickerTitle: String,
    val goalSheetRealTimeLabel: String,
    val goalSheetTimeTypeStopwatch: String,
    val goalSheetTimeTypeTimer: String,
    val goalSheetTimeTypeNone: String,
    val goalSheetLeftTimeLabel: String,
    val goalSheetElapsedTimeLabel: String,
    val goalSheetHomeworkTasksTitle: String,
    val goalSheetDeleteActionLabel: String,
    val goalSheetCompleteActionLabel: String,
    val goalSheetCancelActionLabel: String,
    val homeworksTasksTab: String,
    val todosTasksTab: String,
    val shareHomeworksHeader: String,
    val shareHomeworksPrefixTitle: String,
    val shareHomeworksReceivedTitle: String,
    val shareHomeworksSentTitle: String,
    val shareHomeworksListEmptyTitle: String,
    val sharedHomeworkTasksCountPrefix: String,
    val shareHomeworksButtonTitle: String,
    val tasksProgressTomorrowLabel: String,
    val tasksProgressInTheWeekLabel: String,
    val todosProgressTitle: String,
    val todosProgressLabel: String,
    val homeworkErrorsViewHeader: String,
    val homeworkErrorsTitle: String,
    val homeworksCompletedTitle: String,
    val homeworkExecutionAnalysisHeader: String,
    val comingHomeworksExecutionAnalysisTitle: String,
    val allHomeworksExecutionAnalysisTitle: String,
    val showHomeworkErrorsTitle: String,
    val showSharedHomeworksTitle: String,
    val scopeOfHomeworksHeader: String,
    val homeworksSectionHeader: String,
    val addHomeworkTitle: String,
    val showAllTitle: String,
    val homeworksSectionSubtitle: String,
    val noneTasksTitle: String,
    val noneTodosTitle: String,
    val theoreticalTasksBarName: String,
    val practicalTasksBarName: String,
    val presentationsTasksBarName: String,
    val todosSectionHeader: String,
    val inProgressTodosSectionHeader: String,
    val errorTodosSectionHeader: String,
    val completedTodosSectionHeader: String,
    val totalTodosSuffix: String,
    val showAllTodosTitle: String,
    val untilDeadlineDateSuffix: String,
    val noneDeadlineTitle: String,
    val overdueDeadlineTitle: String,
    val overallHomeworksProgress: String,
    val homeworkTestLabel: String,
    val overdueHomeworksHeader: String,
    val detachedActiveHomeworksHeader: String,
    val overdueTodosHeader: String,
    val noneErrorsTitle: String,
    val receivedHomeworksHeader: String,
    val noneReceivedHomeworksTitle: String,
    val sentHomeworksHeader: String,
    val noneSentHomeworksTitle: String,
    val acceptHomeworkTitle: String,
    val rejectHomeworkTitle: String,
    val cancelSentHomeworkTitle: String,
    val agoSuffix: String,
    val applySharedHomeworksTitle: String,
    val homeworksLinkedHeader: String,
    val homeworksLinkedLabel: String,
    val targetUserSubjectsTitle: String,
    val currentUserSubjectsTitle: String,
    val specifySubjectLabel: String,
    val classesNotFoundLabel: String,
    val subjectSelectorHeader: String,
    val subjectSelectorTitle: String,
    val linkedClassSelectorHeader: String,
    val linkedClassSelectorTitle: String,
    val numberOfClassSuffix: String,
    val attachClassesLabel: String,
    val selectionSubjectStepHeader: String,
    val selectionSubjectStepLabel: String,
    val selectionSubjectStepAction: String,
    val specifyRecipientsStepHeader: String,
    val specifyRecipientsStepLabel: String,
    val specifyRecipientsStepAction: String,
    val currentTimeRangeDesc: String,
    val testLabel: String,
    val otherErrorMessage: String,
) {

    companion object {
        val RUSSIAN = TasksStrings(
            overviewHeader = "Обзор заданий",
            homeworksHeader = "Задания",
            todosHeader = "Задачи",
            dailyGoalsSectionHeader = "Дневные цели",
            goalsViewProgressTitle = "Прогресс",
            goalsViewProgressHomeworkLabel = "Домашние задания",
            goalsViewProgressTodoLabel = "Задачи",
            goalsViewClosestTitle = "Цели на ближайшие дни",
            goalsViewListTitle = "Список целей",
            goalsViewListEmptyTitle = "Список целей пуст",
            deleteGoalWarningTitle = "Предупреждение!",
            deleteGoalWarningText = "Вы действительно хотите удалить цель на день?",
            goalCreatorHeadline = "Планирование",
            goalCreatorTitle = "Установите дневную цель",
            goalCreatorDateFieldTitle = "Дата",
            goalCreatorDateFieldPlaceholder = "Выберите дату",
            goalCreatorDesiredTimeFieldTitle = "Желаемая продолжительность",
            goalCreatorConfirmTitle = "Запланировать",
            goalSheetTimeControlTitle = "Время выполнения",
            goalSheetDesiredTimeLabel = "Планируемое",
            goalSheetDesiredTimePickerTitle = "Планируемое время",
            goalSheetRealTimeLabel = "Настоящее",
            goalSheetTimeTypeStopwatch = "Секундомер",
            goalSheetTimeTypeTimer = "Таймер",
            goalSheetTimeTypeNone = "Без контроля",
            goalSheetLeftTimeLabel = "Осталось",
            goalSheetElapsedTimeLabel = "Прошло",
            goalSheetHomeworkTasksTitle = "Задания",
            goalSheetDeleteActionLabel = "Удалить",
            goalSheetCompleteActionLabel = "Выполнить",
            goalSheetCancelActionLabel = "Отменить",
            homeworksTasksTab = "Домашние задания",
            todosTasksTab = "Задачи",
            shareHomeworksHeader = "Обмен заданиями",
            shareHomeworksPrefixTitle = "Активность: ",
            shareHomeworksReceivedTitle = "Получено",
            shareHomeworksSentTitle = "Отправлено",
            shareHomeworksListEmptyTitle = "Список пуст",
            sharedHomeworkTasksCountPrefix = "Кол-во заданий: ",
            shareHomeworksButtonTitle = "Поделиться",
            tasksProgressTomorrowLabel = "На завтра",
            tasksProgressInTheWeekLabel = "На неделе",
            todosProgressTitle = "Задачи",
            todosProgressLabel = "Ожидают",
            homeworkErrorsViewHeader = "Контроль ошибок",
            homeworkErrorsTitle = "Ошибки",
            homeworksCompletedTitle = "Выполнено",
            homeworkExecutionAnalysisHeader = "Аналитика выполенния",
            comingHomeworksExecutionAnalysisTitle = "Ближайшее время",
            allHomeworksExecutionAnalysisTitle = "За всё время",
            showHomeworkErrorsTitle = "Просмотреть",
            showSharedHomeworksTitle = "Перейти",
            scopeOfHomeworksHeader = "Объём заданий",
            homeworksSectionHeader = "Обзор домашних заданий",
            homeworksSectionSubtitle = "Текущая неделя",
            showAllTitle = "Смотреть все",
            noneTasksTitle = "Задания отсутствуют",
            noneTodosTitle = "Задачи отсутствуют",
            theoreticalTasksBarName = "Теория",
            practicalTasksBarName = "Практика",
            presentationsTasksBarName = "Доклады",
            todosSectionHeader = "Активные задачи",
            inProgressTodosSectionHeader = "В процессе",
            errorTodosSectionHeader = "Пропущено",
            completedTodosSectionHeader = "Выполнено за неделю",
            totalTodosSuffix = "Всего",
            showAllTodosTitle = "Показать все",
            untilDeadlineDateSuffix = "До",
            noneDeadlineTitle = "Без дедлайна",
            overdueDeadlineTitle = "Просрочено",
            overallHomeworksProgress = "Общий прогресс",
            homeworkTestLabel = "Тест",
            overdueHomeworksHeader = "Пропущенные задания",
            detachedActiveHomeworksHeader = "Активные открепленные задания",
            overdueTodosHeader = "Пропущенные задачи",
            noneErrorsTitle = "Ошибки отсутствуют",
            receivedHomeworksHeader = "Полученные задания",
            noneReceivedHomeworksTitle = "Задания отсутствуют",
            sentHomeworksHeader = "Отправленные задания",
            noneSentHomeworksTitle = "Задания отсутствуют",
            acceptHomeworkTitle = "Принять",
            rejectHomeworkTitle = "Отклонить",
            cancelSentHomeworkTitle = "Отменить",
            agoSuffix = "назад",
            applySharedHomeworksTitle = "Добавить",
            addHomeworkTitle = "Добавить задание",
            homeworksLinkedHeader = "Добавление заданий",
            homeworksLinkedLabel = "Свяжите предметы и занятия по названию",
            targetUserSubjectsTitle = "Пользователь",
            currentUserSubjectsTitle = "Вы",
            specifySubjectLabel = "Указать",
            classesNotFoundLabel = "Занятия не найдены",
            subjectSelectorHeader = "Предмет",
            subjectSelectorTitle = "Выберите соответствующий предмет",
            linkedClassSelectorHeader = "Занятие",
            linkedClassSelectorTitle = "Выберите соответствующее занятие",
            numberOfClassSuffix = "занятие",
            attachClassesLabel = "Прикрепите задание",
            selectionSubjectStepHeader = "1. Выбор предметов",
            selectionSubjectStepLabel = "Выберите предметы которыми хотите поделиться",
            selectionSubjectStepAction = "Продолжить",
            specifyRecipientsStepHeader = "2. Укажите пользователей",
            specifyRecipientsStepLabel = "Укажите с кем вы хотите поделиться заданием",
            specifyRecipientsStepAction = "Отправить",
            currentTimeRangeDesc = "Отобразить текущие даты",
            testLabel = "Тест",
            otherErrorMessage = "Ошибка! Обратитесь к разработчику!",
        )
        val ENGLISH = TasksStrings(
            overviewHeader = "Task overview",
            homeworksHeader = "Tasks",
            todosHeader = "Todos",
            dailyGoalsSectionHeader = "Daily goals",
            goalsViewProgressTitle = "Progress",
            goalsViewProgressHomeworkLabel = "Homework",
            goalsViewProgressTodoLabel = "Tasks",
            goalsViewClosestTitle = "Upcoming Goals",
            goalsViewListTitle = "Goals List",
            goalsViewListEmptyTitle = "The list of goals is empty",
            deleteGoalWarningTitle = "Warning!",
            deleteGoalWarningText = "Are you sure you want to delete the daily goal?",
            goalCreatorHeadline = "Planning",
            goalCreatorTitle = "Set a daily goal",
            goalCreatorDateFieldTitle = "Date",
            goalCreatorDateFieldPlaceholder = "Select date",
            goalCreatorDesiredTimeFieldTitle = "Desired duration",
            goalCreatorConfirmTitle = "Schedule",
            goalSheetTimeControlTitle = "Time Control",
            goalSheetDesiredTimeLabel = "Desired",
            goalSheetDesiredTimePickerTitle = "Desired time",
            goalSheetRealTimeLabel = "Actual",
            goalSheetTimeTypeStopwatch = "Stopwatch",
            goalSheetTimeTypeTimer = "Timer",
            goalSheetTimeTypeNone = "No Control",
            goalSheetLeftTimeLabel = "Left",
            goalSheetElapsedTimeLabel = "Time passed",
            goalSheetHomeworkTasksTitle = "Tasks",
            goalSheetDeleteActionLabel = "Delete",
            goalSheetCompleteActionLabel = "Complete",
            goalSheetCancelActionLabel = "Cancel",
            homeworksTasksTab = "Homeworks",
            todosTasksTab = "Todos",
            inProgressTodosSectionHeader = "In progress",
            errorTodosSectionHeader = "Skipped",
            completedTodosSectionHeader = "Completed in a week",
            addHomeworkTitle = "Add homework",
            shareHomeworksHeader = "Task exchange",
            shareHomeworksPrefixTitle = "Last activity: ",
            shareHomeworksReceivedTitle = "Received",
            shareHomeworksSentTitle = "Sent",
            shareHomeworksListEmptyTitle = "The list is empty",
            sharedHomeworkTasksCountPrefix = "Number of tasks: ",
            shareHomeworksButtonTitle = "Share",
            tasksProgressTomorrowLabel = "For tomorrow",
            tasksProgressInTheWeekLabel = "In the week",
            todosProgressTitle = "Todos",
            todosProgressLabel = "Waiting",
            homeworkErrorsViewHeader = "Error control",
            homeworkErrorsTitle = "Errors",
            homeworksCompletedTitle = "Completed",
            showHomeworkErrorsTitle = "View",
            homeworkExecutionAnalysisHeader = "Execution analysis",
            comingHomeworksExecutionAnalysisTitle = "Coming time",
            allHomeworksExecutionAnalysisTitle = "For all the time",
            showSharedHomeworksTitle = "Go over",
            scopeOfHomeworksHeader = "Scope of tasks",
            homeworksSectionHeader = "Review of homeworks",
            homeworksSectionSubtitle = "Current week",
            showAllTitle = "Show all",
            noneTasksTitle = "Tasks are missing",
            noneTodosTitle = "Todos is missing",
            theoreticalTasksBarName = "Theory",
            practicalTasksBarName = "Practice",
            presentationsTasksBarName = "Presentations",
            todosSectionHeader = "Active todos",
            totalTodosSuffix = "Total",
            showAllTodosTitle = "Show all",
            untilDeadlineDateSuffix = "Until",
            noneDeadlineTitle = "No deadline",
            overdueDeadlineTitle = "Overdue",
            overallHomeworksProgress = "Overall progress",
            homeworkTestLabel = "Test",
            overdueHomeworksHeader = "Missed tasks",
            detachedActiveHomeworksHeader = "Active detached tasks",
            overdueTodosHeader = "Missed todos",
            noneErrorsTitle = "There are no errors",
            receivedHomeworksHeader = "Received tasks",
            noneReceivedHomeworksTitle = "Tasks are missing",
            sentHomeworksHeader = "Sent tasks",
            noneSentHomeworksTitle = "Tasks are missing",
            acceptHomeworkTitle = "Accept",
            rejectHomeworkTitle = "Reject",
            cancelSentHomeworkTitle = "Cancel",
            agoSuffix = "ago",
            applySharedHomeworksTitle = "Add",
            homeworksLinkedHeader = "Adding tasks",
            homeworksLinkedLabel = "Link subjects and classes by name",
            targetUserSubjectsTitle = "User",
            currentUserSubjectsTitle = "You",
            specifySubjectLabel = "Specify",
            classesNotFoundLabel = "Classes not found",
            subjectSelectorHeader = "Subject",
            subjectSelectorTitle = "Select the appropriate subject",
            linkedClassSelectorHeader = "Class",
            linkedClassSelectorTitle = "Select the appropriate class",
            numberOfClassSuffix = "class",
            attachClassesLabel = "Attach an class",
            selectionSubjectStepHeader = "1. Selection of subjects",
            selectionSubjectStepLabel = "Select the subjects you want to share",
            selectionSubjectStepAction = "Continue",
            specifyRecipientsStepHeader = "2. Specify the users",
            specifyRecipientsStepLabel = "Please specify who you would like to share this task with",
            specifyRecipientsStepAction = "Send",
            currentTimeRangeDesc = "Display current dates",
            testLabel = "Тест",
            otherErrorMessage = "Error! Contact the developer!",
        )
    }
}

internal val LocalTasksStrings = staticCompositionLocalOf<TasksStrings> {
    error("Tasks Strings is not provided")
}

internal fun fetchTasksStrings(language: StudyAssistantLanguage) = when (language) {
    StudyAssistantLanguage.EN -> TasksStrings.ENGLISH
    StudyAssistantLanguage.RU -> TasksStrings.RUSSIAN
}